movie-app/core/urls.py
from django.urls import path

from .views import MovieList, MovieDetail, CreateVote, UpdateVote, MovieImageUpload, TopMovies, PersonDetail

app_name = 'core'

urlpatterns = [
    path('movies', MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', MovieDetail.as_view(), name='MovieDetail'),
    path('movie/<int:movie_id>/vote', CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id>/image/upload', MovieImageUpload.as_view(), name='MovieImageUpload'),
    path('movies/top', TopMovies.as_view(), name='TopMovies'),
    path('movies/person/<int:pk>', PersonDetail.as_view(), name='PersonDetail'),
]

movie-app/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import RegisterView

app_name = 'user'

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

movie-app/core/models.py
from django.db import models
from django.db.models.aggregates import Sum
from django.conf import settings

from uuid import uuid4

from config import dev_settings

# Create your models here.


class MovieManager(models.Manager):

    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related(
            'director'
        )
        qs = qs.prefetch_related(
            'writers',
            'actors'
        )
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(
            vote_sum=Sum('vote__value')
        )
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by('-vote_sum')
        qs = qs[:limit]
        return qs


class Movie(models.Model):
    # best practice for creating choice fields, integer values to be saved to the database
    # and string values to be displayed to users
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance' 'Suggested'),
        (RATED_R, 'R - Restricted'),
    )

    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    director = models.ForeignKey(
        to="Person",
        on_delete=models.SET_NULL,      # set the director field to null if the person it's linked to is deleted
        related_name="directed",        # for specifying reverse relations e.g person.directed.all()
        null=True,
        blank=True
    )
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True
    )
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True
    )

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} = {}'.format(self.title, self.year)


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie'
        )


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return "{}, {} ({}-{})".format(
                self.last_name,
                self.first_name,
                self.born,
                self.died
            )
        return "{}, {} ({})".format(
            self.last_name,
            self.first_name,
            self.born
        )


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    class Meta:
        unique_together = ('movie', 'person', 'name')

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person.id, self.name)


class VoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user
            )
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user
            )


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, "^"),
        (DOWN, "+"),
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')


# a function to return a unix-style custom path, to save uploaded images
def movie_directory_path_with_uuid(instance, filename):
    return '({}/{})'.format(instance.movie_id, uuid4())


class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now=True)
    movie = models.ForeignKey('Movie', related_name='movie_image', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.movie.title} image'


movie-app/core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Vote, Movie, MovieImage


class VoteForm(forms.ModelForm):

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES
    )

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie')


class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True
    )
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )

    class Meta:
        model = MovieImage
        fields = ('image', 'user', 'movie')

movie-app/core/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import (PermissionDenied)
from django.core.cache import cache

from .models import Movie, Person, Vote
from .forms import VoteForm, MovieImageForm
from .mixins import CachePageVaryOnCookieMixin

# Create your views here.


class MovieList(CachePageVaryOnCookieMixin, ListView):
    model = Movie
    context_object_name = "movie_list"
    template_name = "core:MovieList"
    paginate_by = 10


class MovieDetail(DetailView):
    queryset = (
        Movie.objects.all_with_related_persons_and_score()
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_form'] = self.movie_image_form()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse(
                    'core:UpdateVote',
                    kwargs={
                        "movie_id": vote.movie.id,
                        "pk": vote.id
                    }
                )
            else:
                vote_form_url = (
                    reverse(
                        "core:CreateVote",
                        kwargs={
                            "movie_id": self.object.id
                        }
                    )
                )

            vote_form = VoteForm(instance=vote)
            context['vote_form'] = vote_form
            context['vote_form_url'] = vote_form_url

        return context

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()
    template_name = 'core/person_detail.html'


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            "core:MovieDetail", kwargs={'pk': movie_id}
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            "core:MovieDetail", kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user

        if vote.user != user:
            raise PermissionDenied('cannot change another user\'s vote')
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail', kwargs={'pk': movie_id}
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail', kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial_data = super().get_initial()
        initial_data['user'] = self.request.user.id
        initial_data['movie'] = self.kwargs['movie_id']
        return initial_data

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk':movie_id}
        )
        return movie_detail_url


class TopMovies(ListView):
    template_name = 'core/top_movies_list.html'

    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)
        if cached_qs:
            same_django = cached_qs.django_version == django.get_version()
            if same_django:
                return cached_qs
        qs = Movie.objects.top_movies(limit=limit)
        cache.set(key, qs)
        return qs

movie-app/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.title}} - {{block.super}}
{% endblock title %}

{% block main %}

    <div>
        <h1>{{object}}</h1>
        <p>{{object.plot}}</p>
    </div>

    <ul>
        {% for i in object.movie_image.all %}
            <li><img src="{{i.image.url}}"></li>
        {% endfor %}
    </ul>

    <p>Directed by <a href="{% url 'core:PersonDetail' pk=object.director.pk %}">{{object.director}}</a></p>

{% endblock main %}

{% block sidebar %}
    <div>
        This movie is rated:
        {{movie.get_rating_display}}
    </div>

    {% if image_form %}
        <div>
            <h2>Upload New Image</h2>
            <form method="post"
                  enctype="multipart/form-data"
                  action="{% url 'core:MovieImageUpload' movie_id=object.id %}"> {% csrf_token %}
                {{image_form.as_p}}
                <p>
                    <button>Upload</button>
                </p>
            </form>
        </div>
    {% endif %}

    <div>
        <h2>
            Score: {{object.score|default_if_none:"IBD"}}
        </h2>
    </div>

    <div>
        {% if vote_form %}
            <form method="post" action="{{vote_form_url}}"> {% csrf_token %}
                {{vote_form.as_p}}
                <button>
                    Vote
                </button>
            </form>
        {% else %}
            <p><a href="{% url 'user:login' %}">Log in</a> to vote for this movie</p>
        {% endif %}
    </div>
{% endblock sidebar %}

movie-app/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
All the Movies
{% endblock %}

{% block main %}

<ul>
    {% for movie in movie_list %}
        <li>
            <a href="{% url 'core:MovieDetail' pk=movie.id %}">
                {{movie}}
            </a>
        </li>
    {% endfor %}
</ul>

<!--Pagination-->
    {% if is_paginated %}
        <li>
            <a href="{% url 'core:MovieList' %}?page=1">
            First
            </a>
        </li>

        {% if page_obj.has_previous %}
            <li>
                <a href="{% url 'core:MovieList' %}?page={{page_obj.previous_page_number}}">
                    {{page_obj.previous_page_number}}
                </a>
            </li>
        {% endif %}

        <li>
            <a href="{% url 'core:MovieList' %}?page={{page_obj.number}}">
                {{page_obj.number}}
            </a>
        </li>

        {% if page_obj.has_next %}
            <li>
                <a href="{% url 'core:MovieList' %}?page={{page_obj.next_page_number}}">
                    {{page_obj.next_page_number}}
                </a>
            </li>
        {% endif %}

        <li>
            <a href="{% url 'core:MovieList' %}?page=last">
                Last
            </a>
        </li>

    {% endif %}
{% endblock main %}

movie-app/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.first_name}}
    {{object.last_name}}
{% endblock title %}

{% block main %}

    <h1>{{object}}</h1>

    <h2>Actor</h2>
    <ul>
        {% for role in object.role_set.all %}
            <li>
                <a href="{% url 'core:MovieDetail' role.movie.id %}" >
                    {{role.movie}}
                </a> :
                {{role.name}}
            </li>
        {% endfor %}
    </ul>

    <h2>Writer</h2>
    <ul>
        {% for movie in object.wiriting_credits.all %}
            <li>
                <a href="{% url 'core:MovieDetail' movie.id %}">
                    {{movie}}
                </a>
            </li>
        {% endfor %}
    </ul>

    <h2>Director</h2>
    <ul>
        {% for movie in object.directed.all %}
            <li>
                <a href="{% url 'core:MovieDetail' movie.id %}">
                    {{movie}}
                </a>
            </li>
        {% endfor %}
    </ul>

{% endblock main %}

movie-app/core/templates/core/top_movie_list.html
{% extends "base.html" %}

{% block title %}
    Top 10 Movies
{% endblock title %}

{% block main %}
    <h1>Top 10 Movies</h1>
    <ol>
        {% for movie in object_list %}
        <li>
            <a href="{% url 'core:MovieDetail' pk=movie.id %}"></a>
            {{movie}}
        </li>
        {% endfor %}
    </ol>
{% endblock main %}