movie-app/core/urls.py
from django.urls import path

from .views import MovieList, MovieDetail, CreateVote, UpdateVote, MovieImageUpload, TopMovies, PersonDetail

app_name = 'core'

urlpatterns = [
    path('movies', MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', MovieDetail.as_view(), name='MovieDetail'),
    path('movie/<int:movie_id>/vote', CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>', UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id>/image/upload', MovieImageUpload.as_view(), name='MovieImageUpload'),
    path('movies/top', TopMovies.as_view(), name='TopMovies'),
    path('movies/person/<int:pk>', PersonDetail.as_view(), name='PersonDetail'),
]

movie-app/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import RegisterView

app_name = 'user'

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

movie-app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title%}
        MyMDB
        {% endblock title%}
    </title>

</head>
<body>
    <a href="{% url 'core:MovieList' %}">
        Movies
    </a>
    <aside>
    {% if user.is_authenticated %}
        <a href="{% url 'user:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'user:login' %}">Log in</a> | <a href="{% url 'user:register' %}">Register</a>
    {% endif %}
    </aside>

    {% block main %}

    {% endblock main%}

    {% block sidebar %}
    {% endblock sidebar %}
</body>
</html>